version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: venda-pamonhas-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  postgres:
    image: docker.io/library/postgres:15
    container_name: venda-pamonhas-postgres
    environment:
      POSTGRES_DB: topicos1db
      POSTGRES_USER: topicos1
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
