@startuml diagramaDeClasses

abstract class DefaultEntity <<MappedSuperclass>> {
  -id: Long
  -dataCadastro: LocalDateTime
}

abstract class Pessoa {
  -nome: String
  -email: String
  -telefone: String
}

DefaultEntity <|-- Pessoa

class Cliente {
  -cpf: String
  -dataNascimento: LocalDate
}

Pessoa <|-- Cliente

class EnderecoCliente <<Embeddable>> {
  -rua: String
  -numero: String
  -bairro: String
  -cidade: String
  -estado: String
  -cep: String
}

class EnderecoEntrega <<Embeddable>> {
  -rua: String
  -numero: String
  -bairro: String
  -cidade: String
  -estado: String
  -cep: String
}

Cliente "1" *-- "0..*" EnderecoCliente

enum SaborPamonha {
  DOCE
  SALGADA
}

enum TipoPamonha {
  TRADICIONAL
  COM_QUEIJO
  GOURMET
}

enum UnidadeMedida {
  KG
  GRAMA
  LITRO
  MILILITRO
  UNIDADE
}

enum StatusPedido {
  ABERTO
  PAGO
  CANCELADO
}

class Pamonha {
  -nome: String
  -descricao: String
  -preco: BigDecimal
  -estoque: int
  -tabelaNutricional: TabelaNutricional

  +atualizarTabelaNutricional(): void
}

DefaultEntity <|-- Pamonha

Pamonha --> SaborPamonha
Pamonha --> TipoPamonha

class Receita {
  -descricao: String

  +calcularTabelaNutricional(): TabelaNutricional
}

Pamonha "1" *-- "1" Receita

class ItemReceita {
  -quantidade: double
}

Receita "1" *-- "1..*" ItemReceita

ItemReceita --> UnidadeMedida

class Ingrediente {
  -nome: String
  -precoUnitario: BigDecimal
  -estoque: double
}

DefaultEntity <|-- Ingrediente

ItemReceita "1" o-- "1" Ingrediente

Ingrediente --> UnidadeMedida

class TabelaNutricional {
  -valorEnergetico: double
  -carboidratos: double
  -acucaresTotais: double
  -proteinas: double
  -gordurasTotal: double
  -gordurasSaturadas: double
  -gordurasTrans: double
  -fibrasAlimentares: double
  -sodio: double
}

Ingrediente "1" --> "1" TabelaNutricional
Pamonha "1" --> "1" TabelaNutricional

class CupomDesconto {
  -codigo: String
  -valorDesconto: BigDecimal
  -dataValidade: LocalDate
  -ativo: boolean
}

DefaultEntity <|-- CupomDesconto

class Pedido {
  -data: LocalDateTime
  -total: BigDecimal
  -enderecoEntrega: EnderecoEntrega
}

DefaultEntity <|-- Pedido

Pedido --> StatusPedido
Pedido "1" --> "1" Cliente
Pedido "1" *-- "1" EnderecoEntrega
Pedido "0..1" o-- "1" CupomDesconto

class ItemPedido {
  -quantidade: int
  -precoUnitario: BigDecimal
}

Pedido "1" *-- "1..*" ItemPedido
ItemPedido "1" --> "1" Pamonha

@enduml